In [2]:
x=input("enter")
print("you entered "+x)
x=input()
print("yhousdjhf:  "+x)

you entered 
yhousdjhf:  


hello this is notebook practice

In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b=np.array([[1,2,3],[3,4,5]])
print(b)

[[1 2 3]
 [3 4 5]]


In [6]:
b.shape

(2, 3)

In [7]:
b.dtype

dtype('int32')

In [8]:
b.ndim

2

In [9]:
b=np.array([[1,2,3,3,5,2,2],[3,4,5,2,3,4,3]])
b.shape
b[0,6]

2

In [10]:
b[1,:]

array([3, 4, 5, 2, 3, 4, 3])

All the rows and their 3rd elelment

In [11]:
# get a specific column
print(b[:,2])

[3 5]


In [12]:
# starting index:ending index:step
print(b[1,1:6:2])
print(b[1,1:-1:2]) #same as the above

[4 2 4]
[4 2 4]


In [13]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [15]:
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [16]:
#random decimal number array 
np.random.rand(4,2)

array([[0.8902386 , 0.72353244],
       [0.67913016, 0.64399773],
       [0.65797986, 0.91922833],
       [0.62674825, 0.19700162]])

In [17]:
#identitiy matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [19]:
#[[1. 1. 1. 1. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 0. 9. 0. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 1. 1. 1. 1.]] create this array
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
a=np.array([1,2,3,4,5])


In [21]:
a+2

array([3, 4, 5, 6, 7])

In [22]:
a+2

array([3, 4, 5, 6, 7])

In [23]:
a*2

array([ 2,  4,  6,  8, 10])

In [24]:
a-2

array([-1,  0,  1,  2,  3])

In [25]:
b=np.array([2,2,3,4,8])
a+b

array([ 3,  4,  6,  8, 13])

In [26]:
a**2

array([ 1,  4,  9, 16, 25])

In [27]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [28]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [29]:
# matrix multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [30]:
# find the determinant
c=np.identity(4)
np.linalg.det(c)

1.0

In [31]:
# statistics


In [32]:
stats=np.array([[1,2,3,4],[4,5,6,4]])
stats

array([[1, 2, 3, 4],
       [4, 5, 6, 4]])

In [33]:
np.min(stats)

1

In [34]:
np.max(stats,axis=0)

array([4, 5, 6, 4])

In [35]:
after=stats.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 4]]])

In [36]:
#vertically stacking matrices
a=np.array([1,2,3,4])
b=np.array([6,7,8,9])
np.vstack([a,b])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [37]:
# horizontal stacking
a=np.ones((2,4))
b=np.zeros((2,2))
np.hstack((a,b))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

**Load Data From File**

In [38]:
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### *Boolean Masking and Advancecd Indexing*

In [39]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

##### *Indexing array with a list*

In [109]:
a=np.array([1,2,3,4,5,6])
i=np.array([1,3,4])
print(a[i])

[2 4 5]
